//
//  KdbxTestFixture.swift
//  TableProTests
//

import CommonCrypto
import Compression
import Foundation
@testable import TablePro

/// Builds a synthetic KDBX 3.1 file matching JetBrains' layout so the reader can
/// be exercised end to end without a real `c.kdbx`. ChaCha20 inner stream,
/// AES-256-CBC body, AES-KDF key transform, with an optional gzip payload to
/// cover the compressed form real files use.
enum KdbxTestFixture {
    static func makeKdbx(
        mainKey: [UInt8],
        title: String,
        userName: String,
        password: String,
        rounds: UInt64 = 60,
        compressed: Bool = false
    ) -> Data {
        let mainSeed = randomBytes(32)
        let transformSeed = randomBytes(32)
        let encryptionIV = randomBytes(16)
        let protectedStreamKey = randomBytes(32)
        let streamStartBytes = randomBytes(32)

        let digest = sha512(protectedStreamKey)
        var cipher = ChaCha20Cipher(key: Array(digest[0..<32]), nonce: Array(digest[32..<44]))
        let protectedPassword = Data(cipher.process(Array(password.utf8))).base64EncodedString()

        let xml = """
        <?xml version="1.0" encoding="utf-8"?>
        <KeePassFile><Root><Group><Name>IntelliJ Platform</Name>
        <Entry>
        <String><Key>Title</Key><Value>\(title)</Value></String>
        <String><Key>UserName</Key><Value>\(userName)</Value></String>
        <String><Key>Password</Key><Value Protected="True">\(protectedPassword)</Value></String>
        </Entry></Group></Root></KeePassFile>
        """
        let payload = compressed ? gzip(Array(xml.utf8)) : Array(xml.utf8)

        var framed: [UInt8] = []
        framed += le32(0)
        framed += sha256(payload)
        framed += le32(UInt32(payload.count))
        framed += payload
        framed += le32(1)
        framed += [UInt8](repeating: 0, count: 32)
        framed += le32(0)

        let plaintext = streamStartBytes + framed
        let composite = sha256(sha256(mainKey))
        let finalKey = sha256(mainSeed + sha256(aesKdf(composite, seed: transformSeed, rounds: rounds)))
        let ciphertext = aesCBCEncrypt(plaintext, key: finalKey, iv: encryptionIV)

        var header: [UInt8] = []
        header += le32(0x9AA2_D903)
        header += le32(0xB54B_FB67)
        header += le32(0x0003_0001)
        appendField(&header, 3, le32(compressed ? 1 : 0))
        appendField(&header, 4, mainSeed)
        appendField(&header, 5, transformSeed)
        appendField(&header, 6, le64(rounds))
        appendField(&header, 7, encryptionIV)
        appendField(&header, 8, protectedStreamKey)
        appendField(&header, 9, streamStartBytes)
        appendField(&header, 10, le32(3))
        appendField(&header, 0, [0x0d, 0x0a, 0x0d, 0x0a])

        return Data(header + ciphertext)
    }

    /// Encodes `mainKey` the way `c.pwd` stores it: BUILT_IN AES-128-CBC under the
    /// hardcoded "Proxy Config Sec" key, with a big-endian IV-length prefix.
    static func makeMainKeyFile(mainKey: [UInt8]) -> String {
        let iv = randomBytes(16)
        let ciphertext = aesCBCEncrypt(mainKey, key: Array("Proxy Config Sec".utf8), iv: iv)
        var blob = beBytes(UInt32(16))
        blob += iv
        blob += ciphertext
        let base64 = Data(blob).base64EncodedString()
        return "isAutoGenerated: true\nvalue: !!binary \(base64)\nencryption: BUILT_IN\n"
    }

    // MARK: - Crypto Helpers

    static func aesKdf(_ input: [UInt8], seed: [UInt8], rounds: UInt64) -> [UInt8] {
        var cryptor: CCCryptorRef?
        CCCryptorCreate(
            CCOperation(kCCEncrypt),
            CCAlgorithm(kCCAlgorithmAES),
            CCOptions(kCCOptionECBMode),
            seed,
            seed.count,
            nil,
            &cryptor
        )
        guard let cryptor else { return input }
        defer { CCCryptorRelease(cryptor) }

        var current = input
        var next = [UInt8](repeating: 0, count: 32)
        for _ in 0..<rounds {
            var moved = 0
            CCCryptorUpdate(cryptor, current, 32, &next, 32, &moved)
            swap(&current, &next)
        }
        return current
    }

    static func aesCBCEncrypt(_ plaintext: [UInt8], key: [UInt8], iv: [UInt8]) -> [UInt8] {
        var output = [UInt8](repeating: 0, count: plaintext.count + kCCBlockSizeAES128)
        var outputLength = 0
        CCCrypt(
            CCOperation(kCCEncrypt),
            CCAlgorithm(kCCAlgorithmAES),
            CCOptions(kCCOptionPKCS7Padding),
            key,
            key.count,
            iv,
            plaintext,
            plaintext.count,
            &output,
            output.count,
            &outputLength
        )
        return Array(output.prefix(outputLength))
    }

    static func sha256(_ data: [UInt8]) -> [UInt8] {
        var hash = [UInt8](repeating: 0, count: Int(CC_SHA256_DIGEST_LENGTH))
        CC_SHA256(data, CC_LONG(data.count), &hash)
        return hash
    }

    static func sha512(_ data: [UInt8]) -> [UInt8] {
        var hash = [UInt8](repeating: 0, count: Int(CC_SHA512_DIGEST_LENGTH))
        CC_SHA512(data, CC_LONG(data.count), &hash)
        return hash
    }

    static func randomBytes(_ count: Int) -> [UInt8] {
        var bytes = [UInt8](repeating: 0, count: count)
        _ = SecRandomCopyBytes(kSecRandomDefault, count, &bytes)
        return bytes
    }

    // MARK: - Encoding Helpers

    private static func appendField(_ header: inout [UInt8], _ type: UInt8, _ data: [UInt8]) {
        header.append(type)
        header += le16(UInt16(data.count))
        header += data
    }

    static func le16(_ value: UInt16) -> [UInt8] {
        [UInt8(value & 0xff), UInt8((value >> 8) & 0xff)]
    }

    static func le32(_ value: UInt32) -> [UInt8] {
        (0..<4).map { UInt8((value >> (8 * $0)) & 0xff) }
    }

    static func le64(_ value: UInt64) -> [UInt8] {
        (0..<8).map { UInt8((value >> (8 * UInt64($0))) & 0xff) }
    }

    static func beBytes(_ value: UInt32) -> [UInt8] {
        [
            UInt8((value >> 24) & 0xff),
            UInt8((value >> 16) & 0xff),
            UInt8((value >> 8) & 0xff),
            UInt8(value & 0xff)
        ]
    }

    // MARK: - GZIP

    private static func gzip(_ data: [UInt8]) -> [UInt8] {
        var output: [UInt8] = [0x1f, 0x8b, 0x08, 0x00, 0, 0, 0, 0, 0x00, 0xff]
        output += rawDeflate(data)
        output += le32(crc32(data))
        output += le32(UInt32(data.count & 0xffff_ffff))
        return output
    }

    private static func rawDeflate(_ input: [UInt8]) -> [UInt8] {
        let bufferSize = 65_536
        let destination = UnsafeMutablePointer<UInt8>.allocate(capacity: bufferSize)
        defer { destination.deallocate() }

        var stream = compression_stream(dst_ptr: destination, dst_size: bufferSize, src_ptr: destination, src_size: 0, state: nil)
        guard compression_stream_init(&stream, COMPRESSION_STREAM_ENCODE, COMPRESSION_ZLIB) == COMPRESSION_STATUS_OK else {
            return input
        }
        defer { compression_stream_destroy(&stream) }

        return input.withUnsafeBufferPointer { source -> [UInt8] in
            guard let base = source.baseAddress else { return input }
            stream.src_ptr = base
            stream.src_size = source.count
            stream.dst_ptr = destination
            stream.dst_size = bufferSize

            var output: [UInt8] = []
            while true {
                switch compression_stream_process(&stream, Int32(COMPRESSION_STREAM_FINALIZE.rawValue)) {
                case COMPRESSION_STATUS_OK:
                    if stream.dst_size == 0 {
                        output.append(contentsOf: UnsafeBufferPointer(start: destination, count: bufferSize))
                        stream.dst_ptr = destination
                        stream.dst_size = bufferSize
                    }
                case COMPRESSION_STATUS_END:
                    output.append(contentsOf: UnsafeBufferPointer(start: destination, count: bufferSize - stream.dst_size))
                    return output
                default:
                    return input
                }
            }
        }
    }

    private static func crc32(_ data: [UInt8]) -> UInt32 {
        var crc: UInt32 = 0xffff_ffff
        for byte in data {
            crc ^= UInt32(byte)
            for _ in 0..<8 {
                crc = (crc & 1) != 0 ? (crc >> 1) ^ 0xedb8_8320 : crc >> 1
            }
        }
        return crc ^ 0xffff_ffff
    }
}
