/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package damenggo */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdlib.h>
#include <stdint.h>

typedef struct {
    char** names;
    char** typeNames;
    int*   nullables;
    int    count;
} ColumnInfoArray;

typedef struct {
    char** values;
    int*   lengths;
    int*   isNull;
    int    count;
} RowData;

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


/* Return type for DamengOpen */
struct DamengOpen_return {
	void* r0;
	char* r1;
};
extern struct DamengOpen_return DamengOpen(char* dsn);
extern void DamengClose(void* conn);
extern char* DamengPing(void* conn);

/* Return type for DamengBeginTx */
struct DamengBeginTx_return {
	void* r0;
	char* r1;
};
extern struct DamengBeginTx_return DamengBeginTx(void* conn);
extern char* DamengCommitTx(void* txHandle);
extern char* DamengRollbackTx(void* txHandle);

/* Return type for DamengQuery */
struct DamengQuery_return {
	void* r0;
	char* r1;
};
extern struct DamengQuery_return DamengQuery(void* conn, char* sqlStr);

/* Return type for DamengQueryWithParams */
struct DamengQueryWithParams_return {
	void* r0;
	char* r1;
};
extern struct DamengQueryWithParams_return DamengQueryWithParams(void* conn, char* sqlStr, int paramCount, char** paramValues);

/* Return type for DamengExec */
struct DamengExec_return {
	int64_t r0;
	char* r1;
};
extern struct DamengExec_return DamengExec(void* conn, char* sqlStr);

/* Return type for DamengExecWithParams */
struct DamengExecWithParams_return {
	int64_t r0;
	char* r1;
};
extern struct DamengExecWithParams_return DamengExecWithParams(void* conn, char* sqlStr, int paramCount, char** paramValues);
extern int DamengRowsNext(void* rowsHandle);
extern int DamengRowsColumnCount(void* rowsHandle);
extern char** DamengRowsColumnNames(void* rowsHandle);
extern char** DamengRowsColumnTypeNames(void* rowsHandle);
extern char** DamengRowsScanText(void* rowsHandle);
extern char** DamengRowsScanRaw(void* rowsHandle, int* outIsNull);
extern void DamengRowsClose(void* rowsHandle);
extern void DamengFreeString(char* s);
extern void DamengFreeStringArray(char** arr, int count);
extern char* DamengFetchTables(void* conn, char* schema);
extern char* DamengFetchColumns(void* conn, char* schema, char* table);
extern char* DamengFetchVersion(void* conn);
extern char* DamengFetchCurrentSchema(void* conn);
extern char* DamengSetSchema(void* conn, char* schema);

#ifdef __cplusplus
}
#endif
